const mutations = {
  SUCCESS_BANNER_INFO: 'SUCCESS_BANNER_INFO',
  ERROR_BANNER_INFO: 'ERROR_BANNER_INFO',
  SUCCESS_BANNER_INFO_SHOW: 'SUCCESS_BANNER_INFO_SHOW',
  ERROR_BANNER_INFO_SHOW: 'ERROR_BANNER_INFO_SHOW',
  CLEAR_JANJI_POLITIK: 'CLEAR_JANJI_POLITIK',
  SUCCESS_JANJI_POLITIK: 'SUCCESS_JANJI_POLITIK',
  ERROR_JANJI_POLITIK: 'ERROR_JANJI_POLITIK',
  CLEAR_FEEDS_PILPRES: 'CLEAR_FEEDS_PILPRES',
  SUCCESS_FEEDS_PILPRES: 'SUCCESS_FEEDS_PILPRES',
  ERROR_FEEDS_PILPRES: 'ERROR_FEEDS_PILPRES',
  SUCCESS_REPORT: 'SUCCESS_REPORT',
  ERROR_REPORT: 'ERROR_REPORT'
}

export default mutations
