const mutations = {
  SUCCESS_BANNER_INFO: 'SUCCESS_BANNER_INFO',
  ERROR_BANNER_INFO: 'ERROR_BANNER_INFO',
  SUCCESS_BANNER_INFO_SHOW: 'SUCCESS_BANNER_INFO_SHOW',
  ERROR_BANNER_INFO_SHOW: 'ERROR_BANNER_INFO_SHOW',
  CLEAR_JANJI_POLITIK: 'CLEAR_JANJI_POLITIK',
  SUCCESS_JANJI_POLITIK: 'SUCCESS_JANJI_POLITIK',
  ERROR_JANJI_POLITIK: 'ERROR_JANJI_POLITIK'
}

export default mutations
