const mutations = {
  SUCCESS_BANNER_INFO: 'SUCCESS_BANNER_INFO',
  ERROR_BANNER_INFO: 'ERROR_BANNER_INFO',
  SUCCESS_BANNER_INFO_SHOW: 'SUCCESS_BANNER_INFO_SHOW',
  ERROR_BANNER_INFO_SHOW: 'ERROR_BANNER_INFO_SHOW'
}

export default mutations
